
export const CHANGE_HOME_DATA = "home/CHANGE_HOME_DATA"
export const ADD_HOME_LIST = "home/ADD_HOME_LIST"
export const CHANGE_SCROLL_TOP_SHOW = "home/CHANGE_SCROLL_TOP_SHOW"
export const TOGGLE_SCROLL_TOP = "home/TOGGLE_SCROLL_TOP"
